// AUTO-GENERATED by scripts/export-abi.mjs — do not edit.
export const PolicyEngineAbi = [
  {
    "type": "constructor",
    "inputs": [
      {
        "name": "treasury_",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "agentInfo",
    "inputs": [
      {
        "name": "agent",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "tuple",
        "internalType": "struct ITreasury.AgentInfo",
        "components": [
          {
            "name": "active",
            "type": "bool",
            "internalType": "bool"
          },
          {
            "name": "expiresAt",
            "type": "uint64",
            "internalType": "uint64"
          }
        ]
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "evaluate",
    "inputs": [
      {
        "name": "agent",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "recipient",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "amount",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "spentToday",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "spentThisMonth",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "checkVelocity",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "outputs": [
      {
        "name": "r",
        "type": "tuple",
        "internalType": "struct IPolicyEngine.Result",
        "components": [
          {
            "name": "policyLive",
            "type": "bool",
            "internalType": "bool"
          },
          {
            "name": "agentAuthorized",
            "type": "bool",
            "internalType": "bool"
          },
          {
            "name": "agentNotExpired",
            "type": "bool",
            "internalType": "bool"
          },
          {
            "name": "recipientApproved",
            "type": "bool",
            "internalType": "bool"
          },
          {
            "name": "amountPositive",
            "type": "bool",
            "internalType": "bool"
          },
          {
            "name": "withinTxLimit",
            "type": "bool",
            "internalType": "bool"
          },
          {
            "name": "withinDailyLimit",
            "type": "bool",
            "internalType": "bool"
          },
          {
            "name": "withinMonthlyLimit",
            "type": "bool",
            "internalType": "bool"
          },
          {
            "name": "requiresApproval",
            "type": "bool",
            "internalType": "bool"
          }
        ]
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "isRecipient",
    "inputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "policy",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "tuple",
        "internalType": "struct ITreasury.Policy",
        "components": [
          {
            "name": "maxTransactionAmount",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "dailyLimit",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "monthlyLimit",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "approvalThreshold",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "expiresAt",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "active",
            "type": "bool",
            "internalType": "bool"
          }
        ]
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "recipientMetadata",
    "inputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "setAgent",
    "inputs": [
      {
        "name": "agent",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "expiresAt",
        "type": "uint64",
        "internalType": "uint64"
      },
      {
        "name": "active",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "setPolicy",
    "inputs": [
      {
        "name": "p",
        "type": "tuple",
        "internalType": "struct ITreasury.Policy",
        "components": [
          {
            "name": "maxTransactionAmount",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "dailyLimit",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "monthlyLimit",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "approvalThreshold",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "expiresAt",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "active",
            "type": "bool",
            "internalType": "bool"
          }
        ]
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "setRecipient",
    "inputs": [
      {
        "name": "recipient",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "approved",
        "type": "bool",
        "internalType": "bool"
      },
      {
        "name": "metadataHash",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "treasury",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "view"
  }
] as const;
