// Regenerates packages/sdk/src/abi/*.ts from forge artifacts. Run after `forge build`.
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const outDir = resolve(root, "packages/sdk/src/abi");
mkdirSync(outDir, { recursive: true });

for (const name of ["Treasury", "TreasuryFactory", "PolicyEngine"]) {
  const artifact = JSON.parse(readFileSync(resolve(root, `out/${name}.sol/${name}.json`), "utf8"));
  writeFileSync(
    resolve(outDir, `${name}.ts`),
    `// AUTO-GENERATED by scripts/export-abi.mjs — do not edit.\nexport const ${name}Abi = ${JSON.stringify(artifact.abi, null, 2)} as const;\n`,
  );
  console.log(`wrote ${name}.ts (${artifact.abi.length} entries)`);
}
